package com.bar.goods.bean;

public class Property {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.name_id
     *
     * @mbg.generated
     */
    private Integer nameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.value_id
     *
     * @mbg.generated
     */
    private Integer valueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.id
     *
     * @return the value of property.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.id
     *
     * @param id the value for property.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.product_id
     *
     * @return the value of property.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.product_id
     *
     * @param productId the value for property.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.name_id
     *
     * @return the value of property.name_id
     *
     * @mbg.generated
     */
    public Integer getNameId() {
        return nameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.name_id
     *
     * @param nameId the value for property.name_id
     *
     * @mbg.generated
     */
    public void setNameId(Integer nameId) {
        this.nameId = nameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.value_id
     *
     * @return the value of property.value_id
     *
     * @mbg.generated
     */
    public Integer getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.value_id
     *
     * @param valueId the value for property.value_id
     *
     * @mbg.generated
     */
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }
}