package com.bar.goods.bean;

public class PropertyValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.name_id
     *
     * @mbg.generated
     */
    private Integer nameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.img
     *
     * @mbg.generated
     */
    private byte[] img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.id
     *
     * @return the value of property_value.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.id
     *
     * @param id the value for property_value.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.name_id
     *
     * @return the value of property_value.name_id
     *
     * @mbg.generated
     */
    public Integer getNameId() {
        return nameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.name_id
     *
     * @param nameId the value for property_value.name_id
     *
     * @mbg.generated
     */
    public void setNameId(Integer nameId) {
        this.nameId = nameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.value
     *
     * @return the value of property_value.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.value
     *
     * @param value the value for property_value.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.img
     *
     * @return the value of property_value.img
     *
     * @mbg.generated
     */
    public byte[] getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.img
     *
     * @param img the value for property_value.img
     *
     * @mbg.generated
     */
    public void setImg(byte[] img) {
        this.img = img;
    }
}