package com.bar.goods.bean;

public class PropertyName {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_name.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_name.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_name.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_name.is_sale
     *
     * @mbg.generated
     */
    private Integer isSale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_name.id
     *
     * @return the value of property_name.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_name.id
     *
     * @param id the value for property_name.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_name.c_id
     *
     * @return the value of property_name.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_name.c_id
     *
     * @param cId the value for property_name.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_name.title
     *
     * @return the value of property_name.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_name.title
     *
     * @param title the value for property_name.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_name.is_sale
     *
     * @return the value of property_name.is_sale
     *
     * @mbg.generated
     */
    public Integer getIsSale() {
        return isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_name.is_sale
     *
     * @param isSale the value for property_name.is_sale
     *
     * @mbg.generated
     */
    public void setIsSale(Integer isSale) {
        this.isSale = isSale;
    }
}