package com.bar.user.bean;

public class Resources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.grant_key
     *
     * @mbg.generated
     */
    private String grantKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.page_url
     *
     * @mbg.generated
     */
    private String pageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.seq
     *
     * @mbg.generated
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resource_type
     *
     * @mbg.generated
     */
    private Integer resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.id
     *
     * @return the value of resources.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.id
     *
     * @param id the value for resources.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.name
     *
     * @return the value of resources.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.name
     *
     * @param name the value for resources.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.grant_key
     *
     * @return the value of resources.grant_key
     *
     * @mbg.generated
     */
    public String getGrantKey() {
        return grantKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.grant_key
     *
     * @param grantKey the value for resources.grant_key
     *
     * @mbg.generated
     */
    public void setGrantKey(String grantKey) {
        this.grantKey = grantKey == null ? null : grantKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.page_url
     *
     * @return the value of resources.page_url
     *
     * @mbg.generated
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.page_url
     *
     * @param pageUrl the value for resources.page_url
     *
     * @mbg.generated
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl == null ? null : pageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.seq
     *
     * @return the value of resources.seq
     *
     * @mbg.generated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.seq
     *
     * @param seq the value for resources.seq
     *
     * @mbg.generated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resource_type
     *
     * @return the value of resources.resource_type
     *
     * @mbg.generated
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resource_type
     *
     * @param resourceType the value for resources.resource_type
     *
     * @mbg.generated
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.icon
     *
     * @return the value of resources.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.icon
     *
     * @param icon the value for resources.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.parent_id
     *
     * @return the value of resources.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.parent_id
     *
     * @param parentId the value for resources.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}